### ISSUE TITLE
Execute on a Raspberry Pi

### ISSUE THREAD

**Issue by curly60e** [LN-Juggernaut/juggernaut-desktop#1]
I want to know if there is a way to execute on a Raspberry Pi 4

**Comment by johncantrell97** [comment]
It looks like I can add a build target for armv7l in order to produce a binary that should work on raspberry pi's.  I'll give it a shot tomorrow.

**Comment by curly60e** [comment]
That's cool! Thanks!!

**Comment by johncantrell97** [comment]
Can you try this build? https://github.com/LN-Juggernaut/juggernaut-desktop/releases/download/0.1.1/Juggernaut-linux-armv7l-v0.1.1.AppImage

**Comment by curly60e** [comment]
> Can you try this build? https://github.com/LN-Juggernaut/juggernaut-desktop/releases/download/0.1.1/Juggernaut-linux-armv7l-v0.1.1.AppImage

![image](https://user-images.githubusercontent.com/55191248/79792729-c75cd580-8325-11ea-98b3-75d01e921530.png)


It's working!!!! 

Thanks!!

**Comment by johncantrell97** [comment]
awesome!
