### ISSUE TITLE
Viewing messages -->SendMany

### ISSUE THREAD

**Issue by curly60e** [LN-Juggernaut/juggernaut-desktop#22]
I found an issue if you use both programs, I cannot see some of the messages sended or received from SendMany. And some I sent from my Raspberry I now they are gone if I load the program from Windows.

![image](https://user-images.githubusercontent.com/55191248/80140584-88758c80-857e-11ea-8373-260db5117f25.png)

![image](https://user-images.githubusercontent.com/55191248/80140610-94614e80-857e-11ea-8238-f1c690de7eed.png)

**Comment by johncantrell97** [comment]
yeah, juggernaut has pretty strict constraints currently on what it will accept as a valid message.  There's an issue filed to relax these constraints to allow for easier interoperability between clients.

**Comment by curly60e** [comment]
Well I executed in the terminal of my Raspberry and this is what I found:


./Juggernaut-linux-armv7l-v0.1.1.AppImage 
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(node:26671) UnhandledPromiseRejectionWarning: Error: Cannot find latest-linux-arm.yml in the latest release artifacts (https://github.com/LN-Juggernaut/juggernaut-desktop/releases/download/v0.1.1/latest-linux-arm.yml): HttpError: 404 Not Found
"method: GET url: https://github.com/LN-Juggernaut/juggernaut-desktop/releases/download/v0.1.1/latest-linux-arm.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "date": "Thu, 23 Apr 2020 20:07:57 GMT",
  "content-type": "text/plain; charset=utf-8",
  "server": "GitHub.com",
  "status": "404 Not Found",
  "vary": "X-PJAX, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "1; mode=block",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "set-cookie": [
    "_gh_sess=5aDVgn98%2BcIoslCLuwGuRXWLG94vOWeK3LnZZp%2B9VmNTWglxZg2%2FQ7v6MmRzaXqP1gfA8mCAPCu2FHEuLjdPk5dz4nrOPu%2FDDAWLnTv5M1TLqOVlfrfXGvQqHHgnnOOtsid3QPEtPFAn033te5TcnbS3FFk%2Fal8A0iGtaIxiS5Vt49EeF4hxozdWhykhRHasaFKlpJDcDrs2GecVD7kJpwMZRJAJ9wOx6zy7UtlQ8W48nrU4VscZh8aRdX%2BfExSY%2B7hUM32QjubT1gMJDAGbCg%3D%3D--lQ8U0%2BGDvMtNEraq--mKfEAU452gIDgkqPLxBi9Q%3D%3D; Path=/; HttpOnly; Secure",
    "_octo=GH1.1.1023441715.1587672476; Path=/; Domain=github.com; Expires=Fri, 23 Apr 2021 20:07:56 GMT; Secure",
    "logged_in=no; Path=/; Domain=github.com; Expires=Fri, 23 Apr 2021 20:07:56 GMT; HttpOnly; Secure"
  ],
  "content-length": "40",
  "x-github-request-id": "9302:36B8:50489:67942:5EA1F59C"
}
    at createHttpError (/tmp/.mount_JuggerRYeaCf/resources/app.asar/dist/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:84:10)
    at o.handleResponse (/tmp/.mount_JuggerRYeaCf/resources/app.asar/dist/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:168:14)
    at ClientRequest.<anonymous> (/tmp/.mount_JuggerRYeaCf/resources/app.asar/dist/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:134:16)
    at ClientRequest.emit (events.js:210:5)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2510:12)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
    at newError (/tmp/.mount_JuggerRYeaCf/resources/app.asar/dist/webpack:/node_modules/builder-util-runtime/out/index.js:212:17)
    at t.GitHubProvider.getLatestVersion (/tmp/.mount_JuggerRYeaCf/resources/app.asar/dist/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:134:41)
(node:26671) UnhandledPromiseRejectionWarning: Error: Cannot find latest-linux-arm.yml in the latest release artifacts (https://github.com/LN-Juggernaut/juggernaut-desktop/releases/download/v0.1.1/latest-linux-arm.yml): HttpError: 404 Not Found
"method: GET url: https://github.com/LN-Juggernaut/juggernaut-desktop/releases/download/v0.1.1/latest-linux-arm.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "date": "Thu, 23 Apr 2020 20:07:57 GMT",
  "content-type": "text/plain; charset=utf-8",
  "server": "GitHub.com",
  "status": "404 Not Found",
  "vary": "X-PJAX, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "1; mode=block",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "set-cookie": [
    "_gh_sess=5aDVgn98%2BcIoslCLuwGuRXWLG94vOWeK3LnZZp%2B9VmNTWglxZg2%2FQ7v6MmRzaXqP1gfA8mCAPCu2FHEuLjdPk5dz4nrOPu%2FDDAWLnTv5M1TLqOVlfrfXGvQqHHgnnOOtsid3QPEtPFAn033te5TcnbS3FFk%2Fal8A0iGtaIxiS5Vt49EeF4hxozdWhykhRHasaFKlpJDcDrs2GecVD7kJpwMZRJAJ9wOx6zy7UtlQ8W48nrU4VscZh8aRdX%2BfExSY%2B7hUM32QjubT1gMJDAGbCg%3D%3D--lQ8U0%2BGDvMtNEraq--mKfEAU452gIDgkqPLxBi9Q%3D%3D; Path=/; HttpOnly; Secure",
    "_octo=GH1.1.1023441715.1587672476; Path=/; Domain=github.com; Expires=Fri, 23 Apr 2021 20:07:56 GMT; Secure",
    "logged_in=no; Path=/; Domain=github.com; Expires=Fri, 23 Apr 2021 20:07:56 GMT; HttpOnly; Secure"
  ],
  "content-length": "40",
  "x-github-request-id": "9302:36B8:50489:67942:5EA1F59C"
}
    at createHttpError (/tmp/.mount_JuggerRYeaCf/resources/app.asar/dist/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:84:10)
    at o.handleResponse (/tmp/.mount_JuggerRYeaCf/resources/app.asar/dist/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:168:14)
    at ClientRequest.<anonymous> (/tmp/.mount_JuggerRYeaCf/resources/app.asar/dist/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:134:16)
    at ClientRequest.emit (events.js:210:5)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2510:12)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
    at newError (/tmp/.mount_JuggerRYeaCf/resources/app.asar/dist/webpack:/node_modules/builder-util-runtime/out/index.js:212:17)
    at t.GitHubProvider.getLatestVersion (/tmp/.mount_JuggerRYeaCf/resources/app.asar/dist/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:134:41)
(node:26671) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26671) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26671) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:26671) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by johncantrell97** [comment]
the error you are seeing there is related to the fact that there is no 'update' yml file in github releases for the arm linux build.  There are two issues here.

1) Already exists as open issue with making interop between other clients work better by relaxing validation requirements on incoming messages in Juggernaut
2) There's a bug here if you use the same node on multiple Juggernaut clients your sent messages won't show up in the other client.

**Comment by johncantrell97** [comment]
Closing this as duplicate of #20 and #49
