### ISSUE TITLE
Node Share on chat

### ISSUE THREAD

**Issue by curly60e** [LN-Juggernaut/juggernaut-desktop#24]
Be able to share full node address on messages (+ button) with the other side, and maybe add a button on the other side shared "Open a channel with this node"

**Comment by johncantrell97** [comment]
We already have open issue listed to add 'open channel' to the conversation menu.  I'm not sure what benefit of sharing it in a message like that would be.  I could see maybe having a 'node details' screen you can open for each conversation you have that shows you everything you know about a node (it's channels, payment history, address, pubkey, etc).

**Comment by curly60e** [comment]
I was thinking more like much simpler, adding inside this menu:

![image](https://user-images.githubusercontent.com/55191248/80223926-57996400-861f-11ea-94e8-4a80b21a4332.png)

More like Share node id@ip:port on this chat, and when it share, on the other side should appear like this:

![image](https://user-images.githubusercontent.com/55191248/80224055-916a6a80-861f-11ea-88e9-8adfcec9a00c.png)

Open a channel with this node.

**Comment by johncantrell97** [comment]
@stefan-mihaila already implemented a 'open channel with node' 1-click button in the conversation menu.  I think it's better method than sending a request for someone to open a channel with you as that just adds an unnecessary step.
