### ISSUE TITLE
Opening a channel window bug

### ISSUE THREAD

**Issue by curly60e** [LN-Juggernaut/juggernaut-desktop#28]
I tried to open a channel to you John and it seems that it doesn't work.

On my Raspberry:
![image](https://user-images.githubusercontent.com/55191248/80268582-9e6a7680-867e-11ea-8a6d-b18b191323cf.png)

On my Mac:
![image](https://user-images.githubusercontent.com/55191248/80268593-be019f00-867e-11ea-8cbc-8735e4ceab36.png)

**Comment by johncantrell97** [comment]
yes, this is already fixed -- will be released in v0.1.2 this week.
