### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by curly60e** [LN-Juggernaut/juggernaut-desktop#3]
I don't see coming notifications when I receive messages.
That should be a cool feature to add.

**Comment by johncantrell97** [comment]
Yes, this can be added relatively easily.  Might be annoying though so would want it to be optional.  Currently no settings page exists so I think adding notification settings might require a build out of a settings page.

**Comment by stefan-mihaila** [comment]
@johncantrell97 Maybe close this as a duplicate of https://github.com/LN-Juggernaut/juggernaut-desktop/issues/42?

**Comment by johncantrell97** [comment]
> @johncantrell97 Maybe close this as a duplicate of #42?

Yes 👍

**Comment by johncantrell97** [comment]
Closing as duplicate of #42
