### ISSUE TITLE
Java Error when close program 

### ISSUE THREAD

**Issue by curly60e** [LN-Juggernaut/juggernaut-desktop#5]
![image](https://user-images.githubusercontent.com/55191248/79637668-b65e6980-8157-11ea-9ce5-01082fd609f4.png)

I have this error everytime I close the program.

**Comment by johncantrell97** [comment]
Thanks, this is fixed in next release (0.1.1).  Will publish tomorrow

**Comment by johncantrell97** [comment]
0.1.1 is released, closing this now.
