### ISSUE TITLE
 amount ... pBTC not expressible in msat

### ISSUE THREAD

**Issue by stefan-mihaila** [LN-Juggernaut/juggernaut-desktop#6]
## Prerequisites

- [ ] Using yarn
- [ ] Using node 10.x
- [ ] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [ ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

I should be able to use my node with correct lndconnect string

## Current Behavior

My node is correctly added, but after clicking Launch I get "unable to decode payment request: amount ... pBTC not expressible in msat"

<img width="1112" alt="Screenshot 2020-04-20 at 23 52 16" src="https://user-images.githubusercontent.com/2217136/79799378-065d4c00-8363-11ea-8426-a212876e0862.png">

## Your Environment

- Node version : v13.12.0
- Version or Branch used : Release Version 0.1.1 (0.1.1)
- Operating System and version : macOS Catalina
- lnd: 0.10.0-beta.rc2

my lnd works fine with Zap desktop and mobile using same lndconnect string

**Comment by johncantrell97** [comment]
Thanks for reporting this.  I haven't tried 0.10.0 release yet.  I know there's at least one breaking change introduced in the router SendPayment subservice that needs to be addressed.

I'm not sure if this is related though.  This is a weird one because it's originating from LND.  When Juggernaut is launched it iterates over all your invoices and payments to extract messages from them.  For some reason just iterating over them is causing LND to throw this error.

**Comment by stefan-mihaila** [comment]
maybe there's something wrong with a particular invoice? might be useful to find out which one. let me know if I can help debug this, not really sure where to start.

**Comment by johncantrell97** [comment]
yeah i checked lnd source code and it throws this error when the amount in msats is not evenly divisible by 10.  can you try running 

lncli listpayments
lncli listinvoices

though for invoices if you have more than 100 you would need to page through them using index_offset parameter.

**Comment by stefan-mihaila** [comment]
Okay, I'll try to dig among them and find the culprit.

Maybe the error can aslo be better handled on Junggernaut's side?

**Comment by stefan-mihaila** [comment]
oh, wow

```
lncli listinvoices
[lncli] rpc error: code = Unknown desc = unable to decode payment request: amount ......9541616 pBTC not expressible in msat
```

**Comment by johncantrell97** [comment]
yeah so your invoices are somehow corrupted or malformed.  juggernaut could still probably do a better job of skipping that batch of invoices and continuing.

**Comment by stefan-mihaila** [comment]
https://github.com/lightningnetwork/lnd/issues/4210

Closing this as it's outside the scope of Juggernaut. Only suggestion, but low priority, would be to style error messages coming out of lnd.
