### ISSUE TITLE
Download Mirror for Asia

### ISSUE THREAD

**Issue by bronoman** [LN-Juggernaut/juggernaut-desktop#8]
Suggest to add a list of download mirrors (especially for Asia) as github downloads for both Windows and Linux appear incredibly slow (even on a 1 gbps fibre link in Singapore)
Current estimates: 
- Linux: 12 hrs
- Windows: 2-4 hrs

Usually, this would not take more than 30 sec...

**Comment by johncantrell97** [comment]
wow interesting to hear this.  Do you have this problem on other github releases based projects?

**Comment by bronoman** [comment]
> wow interesting to hear this. Do you have this problem on other github releases based projects?

Just tried it again, just for kicks. ~30 sec. now - I guess an internal github replication issue. Suggest to close this issue for now.
