### ISSUE TITLE
MacOS Cannot read property show of null

### ISSUE THREAD

**Issue by PatrickLemke** [LN-Juggernaut/juggernaut-desktop#9]
## Expected Behavior

In MacOS if I close the app by clicking the x (which minimizes the app) and then reopening it again  the app should be displayed

## Current Behavior

Instead of the app reappearing, the following error occurs:
![image](https://user-images.githubusercontent.com/2649936/79841668-0c314c80-83b8-11ea-9366-719ef810f1ec.png)

## Steps to Reproduce (for bugs)

1. Open App

2. Close app by clicking x

3. Re-open app

## Context

Download 0.1.1 release

## Your Environment

Release: 0.1.1
OS: MacOS 10.15.3

**Comment by LightningK0ala** [comment]
Also seeing this on mac

**Comment by Astro92** [comment]
Can confirm same here

**Comment by johncantrell97** [comment]
thanks for the report, will fix this in a few.

**Comment by johncantrell97** [comment]
this is fixed on master, will be included in next 0.1.2 release.
